apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
  name: postgresql-operator
  namespace: marketplace
spec:
  type: appregistry
  endpoint: https://quay.io/cnr
  registryNamespace: openlabs_operator
  displayName: "Upstream  postgresql-operator Community Operators"
  publisher: "Red Hat"
